// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK1Sjq3gZ43MmjCbpAi10KD8LPcSVeUXE',
    appId: '1:682770824747:web:87daa1093e8aa13c55346e',
    messagingSenderId: '682770824747',
    projectId: 'abuja-rent-direct-5d09a',
    authDomain: 'abuja-rent-direct-5d09a.firebaseapp.com',
    storageBucket: 'abuja-rent-direct-5d09a.firebasestorage.app',
    measurementId: 'G-DR8LFJS7VN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0OpvZAcltsKcXqTQqNZEo6eUwWArP4JE',
    appId: '1:682770824747:android:1d5b3e71b69bae4d55346e',
    messagingSenderId: '682770824747',
    projectId: 'abuja-rent-direct-5d09a',
    storageBucket: 'abuja-rent-direct-5d09a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALKINYeTBT5oB2i67sWERVwMa-SGHLOQA',
    appId: '1:682770824747:ios:2180cb6d853d161555346e',
    messagingSenderId: '682770824747',
    projectId: 'abuja-rent-direct-5d09a',
    storageBucket: 'abuja-rent-direct-5d09a.firebasestorage.app',
    iosBundleId: 'com.example.abujaRentDirect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALKINYeTBT5oB2i67sWERVwMa-SGHLOQA',
    appId: '1:682770824747:ios:2180cb6d853d161555346e',
    messagingSenderId: '682770824747',
    projectId: 'abuja-rent-direct-5d09a',
    storageBucket: 'abuja-rent-direct-5d09a.firebasestorage.app',
    iosBundleId: 'com.example.abujaRentDirect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBK1Sjq3gZ43MmjCbpAi10KD8LPcSVeUXE',
    appId: '1:682770824747:web:cc951256106fc4b155346e',
    messagingSenderId: '682770824747',
    projectId: 'abuja-rent-direct-5d09a',
    authDomain: 'abuja-rent-direct-5d09a.firebaseapp.com',
    storageBucket: 'abuja-rent-direct-5d09a.firebasestorage.app',
    measurementId: 'G-74Z6DXQJCR',
  );

}